# This workflow will upload a Python Package to Github for testing purpose


name: Build Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build package
      run: python setup.py bdist_wheel
    - name: Publish package
      uses: actions/upload-artifact@v3
      with:
        name: $GITHUB_REF
        path: dist/*
